// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseMsg.proto

public final class BaseMsgProto {
  private BaseMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BaseMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the type of msg
     * </pre>
     *
     * <code>int32 msg_type = 1;</code>
     * @return The msgType.
     */
    int getMsgType();

    /**
     * <pre>
     * the sequence number in sender server
     * </pre>
     *
     * <code>int32 msg_sequence_number = 2;</code>
     * @return The msgSequenceNumber.
     */
    int getMsgSequenceNumber();

    /**
     * <pre>
     * the uuid of msg, made up by sender server's id, sequence number and timestamp
     * </pre>
     *
     * <code>int64 msg_uuid = 3;</code>
     * @return The msgUuid.
     */
    long getMsgUuid();

    /**
     * <pre>
     * if this msg is a reply to any action, record the uuid of the msg needed reply
     * </pre>
     *
     * <code>int64 msg_reply_uuid = 4;</code>
     * @return The msgReplyUuid.
     */
    long getMsgReplyUuid();

    /**
     * <pre>
     * sender server id
     * </pre>
     *
     * <code>int32 server_sender_id = 5;</code>
     * @return The serverSenderId.
     */
    int getServerSenderId();

    /**
     * <pre>
     * single receiver server id
     * </pre>
     *
     * <code>int32 server_single_receiver_id = 6;</code>
     * @return The serverSingleReceiverId.
     */
    int getServerSingleReceiverId();

    /**
     * <pre>
     * multi receiver server id
     * </pre>
     *
     * <code>repeated int32 server_multi_receiver_id = 7;</code>
     * @return A list containing the serverMultiReceiverId.
     */
    java.util.List<java.lang.Integer> getServerMultiReceiverIdList();
    /**
     * <pre>
     * multi receiver server id
     * </pre>
     *
     * <code>repeated int32 server_multi_receiver_id = 7;</code>
     * @return The count of serverMultiReceiverId.
     */
    int getServerMultiReceiverIdCount();
    /**
     * <pre>
     * multi receiver server id
     * </pre>
     *
     * <code>repeated int32 server_multi_receiver_id = 7;</code>
     * @param index The index of the element to return.
     * @return The serverMultiReceiverId at the given index.
     */
    int getServerMultiReceiverId(int index);

    /**
     * <pre>
     * if this msg needs timeout in reply
     * </pre>
     *
     * <code>int32 timeout = 8;</code>
     * @return The timeout.
     */
    int getTimeout();

    /**
     * <pre>
     * timestamp, use System.currentTimeMillis()
     * </pre>
     *
     * <code>int64 timestamp = 9;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     * msg reply need number
     * </pre>
     *
     * <code>int32 need_reply_num = 10;</code>
     * @return The needReplyNum.
     */
    int getNeedReplyNum();

    /**
     * <pre>
     * content, maybe json
     * </pre>
     *
     * <code>string content = 11;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <pre>
     * content, maybe json
     * </pre>
     *
     * <code>string content = 11;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code BaseMsg}
   */
  public  static final class BaseMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BaseMsg)
      BaseMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseMsg.newBuilder() to construct.
    private BaseMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseMsg() {
      serverMultiReceiverId_ = emptyIntList();
      content_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BaseMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgType_ = input.readInt32();
              break;
            }
            case 16: {

              msgSequenceNumber_ = input.readInt32();
              break;
            }
            case 24: {

              msgUuid_ = input.readInt64();
              break;
            }
            case 32: {

              msgReplyUuid_ = input.readInt64();
              break;
            }
            case 40: {

              serverSenderId_ = input.readInt32();
              break;
            }
            case 48: {

              serverSingleReceiverId_ = input.readInt32();
              break;
            }
            case 56: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                serverMultiReceiverId_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              serverMultiReceiverId_.addInt(input.readInt32());
              break;
            }
            case 58: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                serverMultiReceiverId_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                serverMultiReceiverId_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 64: {

              timeout_ = input.readInt32();
              break;
            }
            case 72: {

              timestamp_ = input.readInt64();
              break;
            }
            case 80: {

              needReplyNum_ = input.readInt32();
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          serverMultiReceiverId_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseMsgProto.internal_static_BaseMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseMsgProto.internal_static_BaseMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BaseMsgProto.BaseMsg.class, BaseMsgProto.BaseMsg.Builder.class);
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <pre>
     * the type of msg
     * </pre>
     *
     * <code>int32 msg_type = 1;</code>
     * @return The msgType.
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int MSG_SEQUENCE_NUMBER_FIELD_NUMBER = 2;
    private int msgSequenceNumber_;
    /**
     * <pre>
     * the sequence number in sender server
     * </pre>
     *
     * <code>int32 msg_sequence_number = 2;</code>
     * @return The msgSequenceNumber.
     */
    public int getMsgSequenceNumber() {
      return msgSequenceNumber_;
    }

    public static final int MSG_UUID_FIELD_NUMBER = 3;
    private long msgUuid_;
    /**
     * <pre>
     * the uuid of msg, made up by sender server's id, sequence number and timestamp
     * </pre>
     *
     * <code>int64 msg_uuid = 3;</code>
     * @return The msgUuid.
     */
    public long getMsgUuid() {
      return msgUuid_;
    }

    public static final int MSG_REPLY_UUID_FIELD_NUMBER = 4;
    private long msgReplyUuid_;
    /**
     * <pre>
     * if this msg is a reply to any action, record the uuid of the msg needed reply
     * </pre>
     *
     * <code>int64 msg_reply_uuid = 4;</code>
     * @return The msgReplyUuid.
     */
    public long getMsgReplyUuid() {
      return msgReplyUuid_;
    }

    public static final int SERVER_SENDER_ID_FIELD_NUMBER = 5;
    private int serverSenderId_;
    /**
     * <pre>
     * sender server id
     * </pre>
     *
     * <code>int32 server_sender_id = 5;</code>
     * @return The serverSenderId.
     */
    public int getServerSenderId() {
      return serverSenderId_;
    }

    public static final int SERVER_SINGLE_RECEIVER_ID_FIELD_NUMBER = 6;
    private int serverSingleReceiverId_;
    /**
     * <pre>
     * single receiver server id
     * </pre>
     *
     * <code>int32 server_single_receiver_id = 6;</code>
     * @return The serverSingleReceiverId.
     */
    public int getServerSingleReceiverId() {
      return serverSingleReceiverId_;
    }

    public static final int SERVER_MULTI_RECEIVER_ID_FIELD_NUMBER = 7;
    private com.google.protobuf.Internal.IntList serverMultiReceiverId_;
    /**
     * <pre>
     * multi receiver server id
     * </pre>
     *
     * <code>repeated int32 server_multi_receiver_id = 7;</code>
     * @return A list containing the serverMultiReceiverId.
     */
    public java.util.List<java.lang.Integer>
        getServerMultiReceiverIdList() {
      return serverMultiReceiverId_;
    }
    /**
     * <pre>
     * multi receiver server id
     * </pre>
     *
     * <code>repeated int32 server_multi_receiver_id = 7;</code>
     * @return The count of serverMultiReceiverId.
     */
    public int getServerMultiReceiverIdCount() {
      return serverMultiReceiverId_.size();
    }
    /**
     * <pre>
     * multi receiver server id
     * </pre>
     *
     * <code>repeated int32 server_multi_receiver_id = 7;</code>
     * @param index The index of the element to return.
     * @return The serverMultiReceiverId at the given index.
     */
    public int getServerMultiReceiverId(int index) {
      return serverMultiReceiverId_.getInt(index);
    }
    private int serverMultiReceiverIdMemoizedSerializedSize = -1;

    public static final int TIMEOUT_FIELD_NUMBER = 8;
    private int timeout_;
    /**
     * <pre>
     * if this msg needs timeout in reply
     * </pre>
     *
     * <code>int32 timeout = 8;</code>
     * @return The timeout.
     */
    public int getTimeout() {
      return timeout_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 9;
    private long timestamp_;
    /**
     * <pre>
     * timestamp, use System.currentTimeMillis()
     * </pre>
     *
     * <code>int64 timestamp = 9;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int NEED_REPLY_NUM_FIELD_NUMBER = 10;
    private int needReplyNum_;
    /**
     * <pre>
     * msg reply need number
     * </pre>
     *
     * <code>int32 need_reply_num = 10;</code>
     * @return The needReplyNum.
     */
    public int getNeedReplyNum() {
      return needReplyNum_;
    }

    public static final int CONTENT_FIELD_NUMBER = 11;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     * content, maybe json
     * </pre>
     *
     * <code>string content = 11;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * content, maybe json
     * </pre>
     *
     * <code>string content = 11;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (msgType_ != 0) {
        output.writeInt32(1, msgType_);
      }
      if (msgSequenceNumber_ != 0) {
        output.writeInt32(2, msgSequenceNumber_);
      }
      if (msgUuid_ != 0L) {
        output.writeInt64(3, msgUuid_);
      }
      if (msgReplyUuid_ != 0L) {
        output.writeInt64(4, msgReplyUuid_);
      }
      if (serverSenderId_ != 0) {
        output.writeInt32(5, serverSenderId_);
      }
      if (serverSingleReceiverId_ != 0) {
        output.writeInt32(6, serverSingleReceiverId_);
      }
      if (getServerMultiReceiverIdList().size() > 0) {
        output.writeUInt32NoTag(58);
        output.writeUInt32NoTag(serverMultiReceiverIdMemoizedSerializedSize);
      }
      for (int i = 0; i < serverMultiReceiverId_.size(); i++) {
        output.writeInt32NoTag(serverMultiReceiverId_.getInt(i));
      }
      if (timeout_ != 0) {
        output.writeInt32(8, timeout_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(9, timestamp_);
      }
      if (needReplyNum_ != 0) {
        output.writeInt32(10, needReplyNum_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgType_);
      }
      if (msgSequenceNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, msgSequenceNumber_);
      }
      if (msgUuid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, msgUuid_);
      }
      if (msgReplyUuid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, msgReplyUuid_);
      }
      if (serverSenderId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, serverSenderId_);
      }
      if (serverSingleReceiverId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, serverSingleReceiverId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < serverMultiReceiverId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(serverMultiReceiverId_.getInt(i));
        }
        size += dataSize;
        if (!getServerMultiReceiverIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        serverMultiReceiverIdMemoizedSerializedSize = dataSize;
      }
      if (timeout_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, timeout_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, timestamp_);
      }
      if (needReplyNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, needReplyNum_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BaseMsgProto.BaseMsg)) {
        return super.equals(obj);
      }
      BaseMsgProto.BaseMsg other = (BaseMsgProto.BaseMsg) obj;

      if (getMsgType()
          != other.getMsgType()) return false;
      if (getMsgSequenceNumber()
          != other.getMsgSequenceNumber()) return false;
      if (getMsgUuid()
          != other.getMsgUuid()) return false;
      if (getMsgReplyUuid()
          != other.getMsgReplyUuid()) return false;
      if (getServerSenderId()
          != other.getServerSenderId()) return false;
      if (getServerSingleReceiverId()
          != other.getServerSingleReceiverId()) return false;
      if (!getServerMultiReceiverIdList()
          .equals(other.getServerMultiReceiverIdList())) return false;
      if (getTimeout()
          != other.getTimeout()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (getNeedReplyNum()
          != other.getNeedReplyNum()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + MSG_SEQUENCE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getMsgSequenceNumber();
      hash = (37 * hash) + MSG_UUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgUuid());
      hash = (37 * hash) + MSG_REPLY_UUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgReplyUuid());
      hash = (37 * hash) + SERVER_SENDER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getServerSenderId();
      hash = (37 * hash) + SERVER_SINGLE_RECEIVER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getServerSingleReceiverId();
      if (getServerMultiReceiverIdCount() > 0) {
        hash = (37 * hash) + SERVER_MULTI_RECEIVER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getServerMultiReceiverIdList().hashCode();
      }
      hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
      hash = (53 * hash) + getTimeout();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + NEED_REPLY_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getNeedReplyNum();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BaseMsgProto.BaseMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseMsgProto.BaseMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseMsgProto.BaseMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseMsgProto.BaseMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseMsgProto.BaseMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseMsgProto.BaseMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseMsgProto.BaseMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BaseMsgProto.BaseMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BaseMsgProto.BaseMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BaseMsgProto.BaseMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BaseMsgProto.BaseMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BaseMsgProto.BaseMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BaseMsgProto.BaseMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BaseMsg)
        BaseMsgProto.BaseMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseMsgProto.internal_static_BaseMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseMsgProto.internal_static_BaseMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BaseMsgProto.BaseMsg.class, BaseMsgProto.BaseMsg.Builder.class);
      }

      // Construct using BaseMsgProto.BaseMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgType_ = 0;

        msgSequenceNumber_ = 0;

        msgUuid_ = 0L;

        msgReplyUuid_ = 0L;

        serverSenderId_ = 0;

        serverSingleReceiverId_ = 0;

        serverMultiReceiverId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        timeout_ = 0;

        timestamp_ = 0L;

        needReplyNum_ = 0;

        content_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseMsgProto.internal_static_BaseMsg_descriptor;
      }

      @java.lang.Override
      public BaseMsgProto.BaseMsg getDefaultInstanceForType() {
        return BaseMsgProto.BaseMsg.getDefaultInstance();
      }

      @java.lang.Override
      public BaseMsgProto.BaseMsg build() {
        BaseMsgProto.BaseMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public BaseMsgProto.BaseMsg buildPartial() {
        BaseMsgProto.BaseMsg result = new BaseMsgProto.BaseMsg(this);
        int from_bitField0_ = bitField0_;
        result.msgType_ = msgType_;
        result.msgSequenceNumber_ = msgSequenceNumber_;
        result.msgUuid_ = msgUuid_;
        result.msgReplyUuid_ = msgReplyUuid_;
        result.serverSenderId_ = serverSenderId_;
        result.serverSingleReceiverId_ = serverSingleReceiverId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          serverMultiReceiverId_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.serverMultiReceiverId_ = serverMultiReceiverId_;
        result.timeout_ = timeout_;
        result.timestamp_ = timestamp_;
        result.needReplyNum_ = needReplyNum_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BaseMsgProto.BaseMsg) {
          return mergeFrom((BaseMsgProto.BaseMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BaseMsgProto.BaseMsg other) {
        if (other == BaseMsgProto.BaseMsg.getDefaultInstance()) return this;
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (other.getMsgSequenceNumber() != 0) {
          setMsgSequenceNumber(other.getMsgSequenceNumber());
        }
        if (other.getMsgUuid() != 0L) {
          setMsgUuid(other.getMsgUuid());
        }
        if (other.getMsgReplyUuid() != 0L) {
          setMsgReplyUuid(other.getMsgReplyUuid());
        }
        if (other.getServerSenderId() != 0) {
          setServerSenderId(other.getServerSenderId());
        }
        if (other.getServerSingleReceiverId() != 0) {
          setServerSingleReceiverId(other.getServerSingleReceiverId());
        }
        if (!other.serverMultiReceiverId_.isEmpty()) {
          if (serverMultiReceiverId_.isEmpty()) {
            serverMultiReceiverId_ = other.serverMultiReceiverId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureServerMultiReceiverIdIsMutable();
            serverMultiReceiverId_.addAll(other.serverMultiReceiverId_);
          }
          onChanged();
        }
        if (other.getTimeout() != 0) {
          setTimeout(other.getTimeout());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getNeedReplyNum() != 0) {
          setNeedReplyNum(other.getNeedReplyNum());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BaseMsgProto.BaseMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BaseMsgProto.BaseMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgType_ ;
      /**
       * <pre>
       * the type of msg
       * </pre>
       *
       * <code>int32 msg_type = 1;</code>
       * @return The msgType.
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <pre>
       * the type of msg
       * </pre>
       *
       * <code>int32 msg_type = 1;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the type of msg
       * </pre>
       *
       * <code>int32 msg_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private int msgSequenceNumber_ ;
      /**
       * <pre>
       * the sequence number in sender server
       * </pre>
       *
       * <code>int32 msg_sequence_number = 2;</code>
       * @return The msgSequenceNumber.
       */
      public int getMsgSequenceNumber() {
        return msgSequenceNumber_;
      }
      /**
       * <pre>
       * the sequence number in sender server
       * </pre>
       *
       * <code>int32 msg_sequence_number = 2;</code>
       * @param value The msgSequenceNumber to set.
       * @return This builder for chaining.
       */
      public Builder setMsgSequenceNumber(int value) {
        
        msgSequenceNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the sequence number in sender server
       * </pre>
       *
       * <code>int32 msg_sequence_number = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgSequenceNumber() {
        
        msgSequenceNumber_ = 0;
        onChanged();
        return this;
      }

      private long msgUuid_ ;
      /**
       * <pre>
       * the uuid of msg, made up by sender server's id, sequence number and timestamp
       * </pre>
       *
       * <code>int64 msg_uuid = 3;</code>
       * @return The msgUuid.
       */
      public long getMsgUuid() {
        return msgUuid_;
      }
      /**
       * <pre>
       * the uuid of msg, made up by sender server's id, sequence number and timestamp
       * </pre>
       *
       * <code>int64 msg_uuid = 3;</code>
       * @param value The msgUuid to set.
       * @return This builder for chaining.
       */
      public Builder setMsgUuid(long value) {
        
        msgUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the uuid of msg, made up by sender server's id, sequence number and timestamp
       * </pre>
       *
       * <code>int64 msg_uuid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgUuid() {
        
        msgUuid_ = 0L;
        onChanged();
        return this;
      }

      private long msgReplyUuid_ ;
      /**
       * <pre>
       * if this msg is a reply to any action, record the uuid of the msg needed reply
       * </pre>
       *
       * <code>int64 msg_reply_uuid = 4;</code>
       * @return The msgReplyUuid.
       */
      public long getMsgReplyUuid() {
        return msgReplyUuid_;
      }
      /**
       * <pre>
       * if this msg is a reply to any action, record the uuid of the msg needed reply
       * </pre>
       *
       * <code>int64 msg_reply_uuid = 4;</code>
       * @param value The msgReplyUuid to set.
       * @return This builder for chaining.
       */
      public Builder setMsgReplyUuid(long value) {
        
        msgReplyUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * if this msg is a reply to any action, record the uuid of the msg needed reply
       * </pre>
       *
       * <code>int64 msg_reply_uuid = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgReplyUuid() {
        
        msgReplyUuid_ = 0L;
        onChanged();
        return this;
      }

      private int serverSenderId_ ;
      /**
       * <pre>
       * sender server id
       * </pre>
       *
       * <code>int32 server_sender_id = 5;</code>
       * @return The serverSenderId.
       */
      public int getServerSenderId() {
        return serverSenderId_;
      }
      /**
       * <pre>
       * sender server id
       * </pre>
       *
       * <code>int32 server_sender_id = 5;</code>
       * @param value The serverSenderId to set.
       * @return This builder for chaining.
       */
      public Builder setServerSenderId(int value) {
        
        serverSenderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * sender server id
       * </pre>
       *
       * <code>int32 server_sender_id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerSenderId() {
        
        serverSenderId_ = 0;
        onChanged();
        return this;
      }

      private int serverSingleReceiverId_ ;
      /**
       * <pre>
       * single receiver server id
       * </pre>
       *
       * <code>int32 server_single_receiver_id = 6;</code>
       * @return The serverSingleReceiverId.
       */
      public int getServerSingleReceiverId() {
        return serverSingleReceiverId_;
      }
      /**
       * <pre>
       * single receiver server id
       * </pre>
       *
       * <code>int32 server_single_receiver_id = 6;</code>
       * @param value The serverSingleReceiverId to set.
       * @return This builder for chaining.
       */
      public Builder setServerSingleReceiverId(int value) {
        
        serverSingleReceiverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * single receiver server id
       * </pre>
       *
       * <code>int32 server_single_receiver_id = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerSingleReceiverId() {
        
        serverSingleReceiverId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList serverMultiReceiverId_ = emptyIntList();
      private void ensureServerMultiReceiverIdIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          serverMultiReceiverId_ = mutableCopy(serverMultiReceiverId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * multi receiver server id
       * </pre>
       *
       * <code>repeated int32 server_multi_receiver_id = 7;</code>
       * @return A list containing the serverMultiReceiverId.
       */
      public java.util.List<java.lang.Integer>
          getServerMultiReceiverIdList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(serverMultiReceiverId_) : serverMultiReceiverId_;
      }
      /**
       * <pre>
       * multi receiver server id
       * </pre>
       *
       * <code>repeated int32 server_multi_receiver_id = 7;</code>
       * @return The count of serverMultiReceiverId.
       */
      public int getServerMultiReceiverIdCount() {
        return serverMultiReceiverId_.size();
      }
      /**
       * <pre>
       * multi receiver server id
       * </pre>
       *
       * <code>repeated int32 server_multi_receiver_id = 7;</code>
       * @param index The index of the element to return.
       * @return The serverMultiReceiverId at the given index.
       */
      public int getServerMultiReceiverId(int index) {
        return serverMultiReceiverId_.getInt(index);
      }
      /**
       * <pre>
       * multi receiver server id
       * </pre>
       *
       * <code>repeated int32 server_multi_receiver_id = 7;</code>
       * @param index The index to set the value at.
       * @param value The serverMultiReceiverId to set.
       * @return This builder for chaining.
       */
      public Builder setServerMultiReceiverId(
          int index, int value) {
        ensureServerMultiReceiverIdIsMutable();
        serverMultiReceiverId_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * multi receiver server id
       * </pre>
       *
       * <code>repeated int32 server_multi_receiver_id = 7;</code>
       * @param value The serverMultiReceiverId to add.
       * @return This builder for chaining.
       */
      public Builder addServerMultiReceiverId(int value) {
        ensureServerMultiReceiverIdIsMutable();
        serverMultiReceiverId_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * multi receiver server id
       * </pre>
       *
       * <code>repeated int32 server_multi_receiver_id = 7;</code>
       * @param values The serverMultiReceiverId to add.
       * @return This builder for chaining.
       */
      public Builder addAllServerMultiReceiverId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureServerMultiReceiverIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, serverMultiReceiverId_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * multi receiver server id
       * </pre>
       *
       * <code>repeated int32 server_multi_receiver_id = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerMultiReceiverId() {
        serverMultiReceiverId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private int timeout_ ;
      /**
       * <pre>
       * if this msg needs timeout in reply
       * </pre>
       *
       * <code>int32 timeout = 8;</code>
       * @return The timeout.
       */
      public int getTimeout() {
        return timeout_;
      }
      /**
       * <pre>
       * if this msg needs timeout in reply
       * </pre>
       *
       * <code>int32 timeout = 8;</code>
       * @param value The timeout to set.
       * @return This builder for chaining.
       */
      public Builder setTimeout(int value) {
        
        timeout_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * if this msg needs timeout in reply
       * </pre>
       *
       * <code>int32 timeout = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeout() {
        
        timeout_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       * timestamp, use System.currentTimeMillis()
       * </pre>
       *
       * <code>int64 timestamp = 9;</code>
       * @return The timestamp.
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * timestamp, use System.currentTimeMillis()
       * </pre>
       *
       * <code>int64 timestamp = 9;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * timestamp, use System.currentTimeMillis()
       * </pre>
       *
       * <code>int64 timestamp = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int needReplyNum_ ;
      /**
       * <pre>
       * msg reply need number
       * </pre>
       *
       * <code>int32 need_reply_num = 10;</code>
       * @return The needReplyNum.
       */
      public int getNeedReplyNum() {
        return needReplyNum_;
      }
      /**
       * <pre>
       * msg reply need number
       * </pre>
       *
       * <code>int32 need_reply_num = 10;</code>
       * @param value The needReplyNum to set.
       * @return This builder for chaining.
       */
      public Builder setNeedReplyNum(int value) {
        
        needReplyNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * msg reply need number
       * </pre>
       *
       * <code>int32 need_reply_num = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearNeedReplyNum() {
        
        needReplyNum_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * content, maybe json
       * </pre>
       *
       * <code>string content = 11;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * content, maybe json
       * </pre>
       *
       * <code>string content = 11;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * content, maybe json
       * </pre>
       *
       * <code>string content = 11;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * content, maybe json
       * </pre>
       *
       * <code>string content = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * content, maybe json
       * </pre>
       *
       * <code>string content = 11;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BaseMsg)
    }

    // @@protoc_insertion_point(class_scope:BaseMsg)
    private static final BaseMsgProto.BaseMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BaseMsgProto.BaseMsg();
    }

    public static BaseMsgProto.BaseMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseMsg>
        PARSER = new com.google.protobuf.AbstractParser<BaseMsg>() {
      @java.lang.Override
      public BaseMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public BaseMsgProto.BaseMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rBaseMsg.proto\"\216\002\n\007BaseMsg\022\020\n\010msg_type\030" +
      "\001 \001(\005\022\033\n\023msg_sequence_number\030\002 \001(\005\022\020\n\010ms" +
      "g_uuid\030\003 \001(\003\022\026\n\016msg_reply_uuid\030\004 \001(\003\022\030\n\020" +
      "server_sender_id\030\005 \001(\005\022!\n\031server_single_" +
      "receiver_id\030\006 \001(\005\022 \n\030server_multi_receiv" +
      "er_id\030\007 \003(\005\022\017\n\007timeout\030\010 \001(\005\022\021\n\ttimestam" +
      "p\030\t \001(\003\022\026\n\016need_reply_num\030\n \001(\005\022\017\n\007conte" +
      "nt\030\013 \001(\tB\016B\014BaseMsgProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BaseMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseMsg_descriptor,
        new java.lang.String[] { "MsgType", "MsgSequenceNumber", "MsgUuid", "MsgReplyUuid", "ServerSenderId", "ServerSingleReceiverId", "ServerMultiReceiverId", "Timeout", "Timestamp", "NeedReplyNum", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
