package protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseMsg.proto

public final class BaseMsgProto {
  private BaseMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BaseMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 msg_type = 1;</code>
     * @return The msgType.
     */
    int getMsgType();

    /**
     * <code>int32 msg_id = 2;</code>
     * @return The msgId.
     */
    int getMsgId();

    /**
     * <code>int32 reply_msg_id = 3;</code>
     * @return The replyMsgId.
     */
    int getReplyMsgId();

    /**
     * <code>int32 sender_id = 4;</code>
     * @return The senderId.
     */
    int getSenderId();

    /**
     * <code>int32 single_receiver_id = 5;</code>
     * @return The singleReceiverId.
     */
    int getSingleReceiverId();

    /**
     * <code>repeated int32 multi_receiver_id = 6;</code>
     * @return A list containing the multiReceiverId.
     */
    java.util.List<Integer> getMultiReceiverIdList();
    /**
     * <code>repeated int32 multi_receiver_id = 6;</code>
     * @return The count of multiReceiverId.
     */
    int getMultiReceiverIdCount();
    /**
     * <code>repeated int32 multi_receiver_id = 6;</code>
     * @param index The index of the element to return.
     * @return The multiReceiverId at the given index.
     */
    int getMultiReceiverId(int index);

    /**
     * <code>int32 single_reply_id = 7;</code>
     * @return The singleReplyId.
     */
    int getSingleReplyId();

    /**
     * <code>int32 single_reply_msg_id = 8;</code>
     * @return The singleReplyMsgId.
     */
    int getSingleReplyMsgId();

    /**
     * <code>int64 timeout = 9;</code>
     * @return The timeout.
     */
    long getTimeout();

    /**
     * <code>int64 timestamp = 10;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>string content = 11;</code>
     * @return The content.
     */
    String getContent();
    /**
     * <code>string content = 11;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code BaseMsg}
   */
  public  static final class BaseMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BaseMsg)
      BaseMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseMsg.newBuilder() to construct.
    private BaseMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseMsg() {
      multiReceiverId_ = emptyIntList();
      content_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new BaseMsg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgType_ = input.readInt32();
              break;
            }
            case 16: {

              msgId_ = input.readInt32();
              break;
            }
            case 24: {

              replyMsgId_ = input.readInt32();
              break;
            }
            case 32: {

              senderId_ = input.readInt32();
              break;
            }
            case 40: {

              singleReceiverId_ = input.readInt32();
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                multiReceiverId_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              multiReceiverId_.addInt(input.readInt32());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                multiReceiverId_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                multiReceiverId_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 56: {

              singleReplyId_ = input.readInt32();
              break;
            }
            case 64: {

              singleReplyMsgId_ = input.readInt32();
              break;
            }
            case 72: {

              timeout_ = input.readInt64();
              break;
            }
            case 80: {

              timestamp_ = input.readInt64();
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          multiReceiverId_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseMsgProto.internal_static_BaseMsg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseMsgProto.internal_static_BaseMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BaseMsg.class, Builder.class);
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <code>int32 msg_type = 1;</code>
     * @return The msgType.
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int MSG_ID_FIELD_NUMBER = 2;
    private int msgId_;
    /**
     * <code>int32 msg_id = 2;</code>
     * @return The msgId.
     */
    public int getMsgId() {
      return msgId_;
    }

    public static final int REPLY_MSG_ID_FIELD_NUMBER = 3;
    private int replyMsgId_;
    /**
     * <code>int32 reply_msg_id = 3;</code>
     * @return The replyMsgId.
     */
    public int getReplyMsgId() {
      return replyMsgId_;
    }

    public static final int SENDER_ID_FIELD_NUMBER = 4;
    private int senderId_;
    /**
     * <code>int32 sender_id = 4;</code>
     * @return The senderId.
     */
    public int getSenderId() {
      return senderId_;
    }

    public static final int SINGLE_RECEIVER_ID_FIELD_NUMBER = 5;
    private int singleReceiverId_;
    /**
     * <code>int32 single_receiver_id = 5;</code>
     * @return The singleReceiverId.
     */
    public int getSingleReceiverId() {
      return singleReceiverId_;
    }

    public static final int MULTI_RECEIVER_ID_FIELD_NUMBER = 6;
    private com.google.protobuf.Internal.IntList multiReceiverId_;
    /**
     * <code>repeated int32 multi_receiver_id = 6;</code>
     * @return A list containing the multiReceiverId.
     */
    public java.util.List<Integer>
        getMultiReceiverIdList() {
      return multiReceiverId_;
    }
    /**
     * <code>repeated int32 multi_receiver_id = 6;</code>
     * @return The count of multiReceiverId.
     */
    public int getMultiReceiverIdCount() {
      return multiReceiverId_.size();
    }
    /**
     * <code>repeated int32 multi_receiver_id = 6;</code>
     * @param index The index of the element to return.
     * @return The multiReceiverId at the given index.
     */
    public int getMultiReceiverId(int index) {
      return multiReceiverId_.getInt(index);
    }
    private int multiReceiverIdMemoizedSerializedSize = -1;

    public static final int SINGLE_REPLY_ID_FIELD_NUMBER = 7;
    private int singleReplyId_;
    /**
     * <code>int32 single_reply_id = 7;</code>
     * @return The singleReplyId.
     */
    public int getSingleReplyId() {
      return singleReplyId_;
    }

    public static final int SINGLE_REPLY_MSG_ID_FIELD_NUMBER = 8;
    private int singleReplyMsgId_;
    /**
     * <code>int32 single_reply_msg_id = 8;</code>
     * @return The singleReplyMsgId.
     */
    public int getSingleReplyMsgId() {
      return singleReplyMsgId_;
    }

    public static final int TIMEOUT_FIELD_NUMBER = 9;
    private long timeout_;
    /**
     * <code>int64 timeout = 9;</code>
     * @return The timeout.
     */
    public long getTimeout() {
      return timeout_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 10;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 10;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int CONTENT_FIELD_NUMBER = 11;
    private volatile Object content_;
    /**
     * <code>string content = 11;</code>
     * @return The content.
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 11;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (msgType_ != 0) {
        output.writeInt32(1, msgType_);
      }
      if (msgId_ != 0) {
        output.writeInt32(2, msgId_);
      }
      if (replyMsgId_ != 0) {
        output.writeInt32(3, replyMsgId_);
      }
      if (senderId_ != 0) {
        output.writeInt32(4, senderId_);
      }
      if (singleReceiverId_ != 0) {
        output.writeInt32(5, singleReceiverId_);
      }
      if (getMultiReceiverIdList().size() > 0) {
        output.writeUInt32NoTag(50);
        output.writeUInt32NoTag(multiReceiverIdMemoizedSerializedSize);
      }
      for (int i = 0; i < multiReceiverId_.size(); i++) {
        output.writeInt32NoTag(multiReceiverId_.getInt(i));
      }
      if (singleReplyId_ != 0) {
        output.writeInt32(7, singleReplyId_);
      }
      if (singleReplyMsgId_ != 0) {
        output.writeInt32(8, singleReplyMsgId_);
      }
      if (timeout_ != 0L) {
        output.writeInt64(9, timeout_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(10, timestamp_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, content_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgType_);
      }
      if (msgId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, msgId_);
      }
      if (replyMsgId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, replyMsgId_);
      }
      if (senderId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, senderId_);
      }
      if (singleReceiverId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, singleReceiverId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < multiReceiverId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(multiReceiverId_.getInt(i));
        }
        size += dataSize;
        if (!getMultiReceiverIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        multiReceiverIdMemoizedSerializedSize = dataSize;
      }
      if (singleReplyId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, singleReplyId_);
      }
      if (singleReplyMsgId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, singleReplyMsgId_);
      }
      if (timeout_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, timeout_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, timestamp_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BaseMsg)) {
        return super.equals(obj);
      }
      BaseMsg other = (BaseMsg) obj;

      if (getMsgType()
          != other.getMsgType()) return false;
      if (getMsgId()
          != other.getMsgId()) return false;
      if (getReplyMsgId()
          != other.getReplyMsgId()) return false;
      if (getSenderId()
          != other.getSenderId()) return false;
      if (getSingleReceiverId()
          != other.getSingleReceiverId()) return false;
      if (!getMultiReceiverIdList()
          .equals(other.getMultiReceiverIdList())) return false;
      if (getSingleReplyId()
          != other.getSingleReplyId()) return false;
      if (getSingleReplyMsgId()
          != other.getSingleReplyMsgId()) return false;
      if (getTimeout()
          != other.getTimeout()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId();
      hash = (37 * hash) + REPLY_MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + getReplyMsgId();
      hash = (37 * hash) + SENDER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderId();
      hash = (37 * hash) + SINGLE_RECEIVER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSingleReceiverId();
      if (getMultiReceiverIdCount() > 0) {
        hash = (37 * hash) + MULTI_RECEIVER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getMultiReceiverIdList().hashCode();
      }
      hash = (37 * hash) + SINGLE_REPLY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSingleReplyId();
      hash = (37 * hash) + SINGLE_REPLY_MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSingleReplyMsgId();
      hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeout());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BaseMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BaseMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BaseMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BaseMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BaseMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BaseMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BaseMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BaseMsg)
        BaseMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseMsgProto.internal_static_BaseMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseMsgProto.internal_static_BaseMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BaseMsg.class, Builder.class);
      }

      // Construct using BaseMsgProto.BaseMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgType_ = 0;

        msgId_ = 0;

        replyMsgId_ = 0;

        senderId_ = 0;

        singleReceiverId_ = 0;

        multiReceiverId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        singleReplyId_ = 0;

        singleReplyMsgId_ = 0;

        timeout_ = 0L;

        timestamp_ = 0L;

        content_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseMsgProto.internal_static_BaseMsg_descriptor;
      }

      @Override
      public BaseMsg getDefaultInstanceForType() {
        return BaseMsg.getDefaultInstance();
      }

      @Override
      public BaseMsg build() {
        BaseMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BaseMsg buildPartial() {
        BaseMsg result = new BaseMsg(this);
        int from_bitField0_ = bitField0_;
        result.msgType_ = msgType_;
        result.msgId_ = msgId_;
        result.replyMsgId_ = replyMsgId_;
        result.senderId_ = senderId_;
        result.singleReceiverId_ = singleReceiverId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          multiReceiverId_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.multiReceiverId_ = multiReceiverId_;
        result.singleReplyId_ = singleReplyId_;
        result.singleReplyMsgId_ = singleReplyMsgId_;
        result.timeout_ = timeout_;
        result.timestamp_ = timestamp_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BaseMsg) {
          return mergeFrom((BaseMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BaseMsg other) {
        if (other == BaseMsg.getDefaultInstance()) return this;
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (other.getMsgId() != 0) {
          setMsgId(other.getMsgId());
        }
        if (other.getReplyMsgId() != 0) {
          setReplyMsgId(other.getReplyMsgId());
        }
        if (other.getSenderId() != 0) {
          setSenderId(other.getSenderId());
        }
        if (other.getSingleReceiverId() != 0) {
          setSingleReceiverId(other.getSingleReceiverId());
        }
        if (!other.multiReceiverId_.isEmpty()) {
          if (multiReceiverId_.isEmpty()) {
            multiReceiverId_ = other.multiReceiverId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMultiReceiverIdIsMutable();
            multiReceiverId_.addAll(other.multiReceiverId_);
          }
          onChanged();
        }
        if (other.getSingleReplyId() != 0) {
          setSingleReplyId(other.getSingleReplyId());
        }
        if (other.getSingleReplyMsgId() != 0) {
          setSingleReplyMsgId(other.getSingleReplyMsgId());
        }
        if (other.getTimeout() != 0L) {
          setTimeout(other.getTimeout());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BaseMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BaseMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgType_ ;
      /**
       * <code>int32 msg_type = 1;</code>
       * @return The msgType.
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>int32 msg_type = 1;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 msg_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private int msgId_ ;
      /**
       * <code>int32 msg_id = 2;</code>
       * @return The msgId.
       */
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <code>int32 msg_id = 2;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(int value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 msg_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        
        msgId_ = 0;
        onChanged();
        return this;
      }

      private int replyMsgId_ ;
      /**
       * <code>int32 reply_msg_id = 3;</code>
       * @return The replyMsgId.
       */
      public int getReplyMsgId() {
        return replyMsgId_;
      }
      /**
       * <code>int32 reply_msg_id = 3;</code>
       * @param value The replyMsgId to set.
       * @return This builder for chaining.
       */
      public Builder setReplyMsgId(int value) {
        
        replyMsgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 reply_msg_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReplyMsgId() {
        
        replyMsgId_ = 0;
        onChanged();
        return this;
      }

      private int senderId_ ;
      /**
       * <code>int32 sender_id = 4;</code>
       * @return The senderId.
       */
      public int getSenderId() {
        return senderId_;
      }
      /**
       * <code>int32 sender_id = 4;</code>
       * @param value The senderId to set.
       * @return This builder for chaining.
       */
      public Builder setSenderId(int value) {
        
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sender_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderId() {
        
        senderId_ = 0;
        onChanged();
        return this;
      }

      private int singleReceiverId_ ;
      /**
       * <code>int32 single_receiver_id = 5;</code>
       * @return The singleReceiverId.
       */
      public int getSingleReceiverId() {
        return singleReceiverId_;
      }
      /**
       * <code>int32 single_receiver_id = 5;</code>
       * @param value The singleReceiverId to set.
       * @return This builder for chaining.
       */
      public Builder setSingleReceiverId(int value) {
        
        singleReceiverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 single_receiver_id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSingleReceiverId() {
        
        singleReceiverId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList multiReceiverId_ = emptyIntList();
      private void ensureMultiReceiverIdIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          multiReceiverId_ = mutableCopy(multiReceiverId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 multi_receiver_id = 6;</code>
       * @return A list containing the multiReceiverId.
       */
      public java.util.List<Integer>
          getMultiReceiverIdList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(multiReceiverId_) : multiReceiverId_;
      }
      /**
       * <code>repeated int32 multi_receiver_id = 6;</code>
       * @return The count of multiReceiverId.
       */
      public int getMultiReceiverIdCount() {
        return multiReceiverId_.size();
      }
      /**
       * <code>repeated int32 multi_receiver_id = 6;</code>
       * @param index The index of the element to return.
       * @return The multiReceiverId at the given index.
       */
      public int getMultiReceiverId(int index) {
        return multiReceiverId_.getInt(index);
      }
      /**
       * <code>repeated int32 multi_receiver_id = 6;</code>
       * @param index The index to set the value at.
       * @param value The multiReceiverId to set.
       * @return This builder for chaining.
       */
      public Builder setMultiReceiverId(
          int index, int value) {
        ensureMultiReceiverIdIsMutable();
        multiReceiverId_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 multi_receiver_id = 6;</code>
       * @param value The multiReceiverId to add.
       * @return This builder for chaining.
       */
      public Builder addMultiReceiverId(int value) {
        ensureMultiReceiverIdIsMutable();
        multiReceiverId_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 multi_receiver_id = 6;</code>
       * @param values The multiReceiverId to add.
       * @return This builder for chaining.
       */
      public Builder addAllMultiReceiverId(
          Iterable<? extends Integer> values) {
        ensureMultiReceiverIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, multiReceiverId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 multi_receiver_id = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMultiReceiverId() {
        multiReceiverId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private int singleReplyId_ ;
      /**
       * <code>int32 single_reply_id = 7;</code>
       * @return The singleReplyId.
       */
      public int getSingleReplyId() {
        return singleReplyId_;
      }
      /**
       * <code>int32 single_reply_id = 7;</code>
       * @param value The singleReplyId to set.
       * @return This builder for chaining.
       */
      public Builder setSingleReplyId(int value) {
        
        singleReplyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 single_reply_id = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSingleReplyId() {
        
        singleReplyId_ = 0;
        onChanged();
        return this;
      }

      private int singleReplyMsgId_ ;
      /**
       * <code>int32 single_reply_msg_id = 8;</code>
       * @return The singleReplyMsgId.
       */
      public int getSingleReplyMsgId() {
        return singleReplyMsgId_;
      }
      /**
       * <code>int32 single_reply_msg_id = 8;</code>
       * @param value The singleReplyMsgId to set.
       * @return This builder for chaining.
       */
      public Builder setSingleReplyMsgId(int value) {
        
        singleReplyMsgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 single_reply_msg_id = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSingleReplyMsgId() {
        
        singleReplyMsgId_ = 0;
        onChanged();
        return this;
      }

      private long timeout_ ;
      /**
       * <code>int64 timeout = 9;</code>
       * @return The timeout.
       */
      public long getTimeout() {
        return timeout_;
      }
      /**
       * <code>int64 timeout = 9;</code>
       * @param value The timeout to set.
       * @return This builder for chaining.
       */
      public Builder setTimeout(long value) {
        
        timeout_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timeout = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeout() {
        
        timeout_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 10;</code>
       * @return The timestamp.
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 10;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 11;</code>
       * @return The content.
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 11;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 11;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 11;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BaseMsg)
    }

    // @@protoc_insertion_point(class_scope:BaseMsg)
    private static final BaseMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BaseMsg();
    }

    public static BaseMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseMsg>
        PARSER = new com.google.protobuf.AbstractParser<BaseMsg>() {
      @Override
      public BaseMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BaseMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public BaseMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rBaseMsg.proto\"\366\001\n\007BaseMsg\022\020\n\010msg_type\030" +
      "\001 \001(\005\022\016\n\006msg_id\030\002 \001(\005\022\024\n\014reply_msg_id\030\003 " +
      "\001(\005\022\021\n\tsender_id\030\004 \001(\005\022\032\n\022single_receive" +
      "r_id\030\005 \001(\005\022\031\n\021multi_receiver_id\030\006 \003(\005\022\027\n" +
      "\017single_reply_id\030\007 \001(\005\022\033\n\023single_reply_m" +
      "sg_id\030\010 \001(\005\022\017\n\007timeout\030\t \001(\003\022\021\n\ttimestam" +
      "p\030\n \001(\003\022\017\n\007content\030\013 \001(\tB\016B\014BaseMsgProto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BaseMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseMsg_descriptor,
        new String[] { "MsgType", "MsgId", "ReplyMsgId", "SenderId", "SingleReceiverId", "MultiReceiverId", "SingleReplyId", "SingleReplyMsgId", "Timeout", "Timestamp", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
